provenance:
  _type: https://in-toto.io/Statement/v1
  subject:
  - name: .github/workflows/release.yaml
    digest:
      sha256: 5983bb680dcbdd12dfcab4f499d7c2f51354b6b8404af64e5a3c3d2ae423c4b1
  predicate:
    buildDefinition:
      buildType: https://github.com/N4M3Z/forge-cli/init/v1
      externalParameters:
        source: https://github.com/N4M3Z/forge-cli
      resolvedDependencies:
      - uri: templates/init/.github/workflows/release.yaml
        digest:
          sha256: 5983bb680dcbdd12dfcab4f499d7c2f51354b6b8404af64e5a3c3d2ae423c4b1
    runDetails:
      builder:
        id: forge-cli
        version:
          forge: 0.3.2
      metadata:
        startedOn: 2026-06-16T22:30:08.939684+00:00
