provenance:
  _type: https://in-toto.io/Statement/v1
  subject:
  - name: .gitlab-ci.yml
    digest:
      sha256: 6d6e7f590b272a4c636d69e8a939717c6bb2a189fe4f439ba64aed8150fe4a6f
  predicate:
    buildDefinition:
      buildType: https://github.com/N4M3Z/forge-cli/init/v1
      externalParameters:
        source: https://github.com/N4M3Z/forge-cli
      resolvedDependencies:
      - uri: templates/init/.gitlab-ci.yml
        digest:
          sha256: 6d6e7f590b272a4c636d69e8a939717c6bb2a189fe4f439ba64aed8150fe4a6f
    runDetails:
      builder:
        id: forge-cli
        version:
          forge: 0.3.2
      metadata:
        startedOn: 2026-06-16T22:30:08.939861+00:00
